### ISSUE TITLE
Using server paging on a function causes problem 

### ISSUE THREAD

**Issue by johanparmar** [object/Simple.OData.Client#110]
Hi,

It seems like when we use paging on something that is a function it stops working when it tries to run the tne next link. The code looks like this:
```
        public void GenerateFullFile()
        {
            var skuTypeIdToExclude = SkuStatusType.WaitingForErp.SkuTypeId;
            var skuStatusIdToExclude = SkuStatus.Inactive.StatusId;
            var annotations = new ODataFeedAnnotations();
            var items = oDataClient.For<ClientProductSku>()
                .Function(FunctionNameExportProductFull)
                .Set(new { clientId, skuTypeIdToExclude, skuStatusIdToExclude })
                .Expand(ExportProductExpandTables)
                .FindEntriesAsync(annotations)
                .Result;

            using (var generator = new ExportProductStreamingXmlFileGenerator(FileType.Full))
            {
                generator.GenerateStartXmlDocument();
                WriteItemsToFile(items, generator);
                while (annotations.NextPageLink != null)
                {
                    items = oDataClient.For<ClientProductSku>()
                        .Function(FunctionNameExportProductFull)
                        .Set(new { clientId, skuTypeIdToExclude, skuStatusIdToExclude })
                        .Expand(ExportProductExpandTables)
                        .FindEntriesAsync(annotations.NextPageLink, annotations)
                        .Result;
                    WriteItemsToFile(items, generator);
                }
                generator.GenerateEndXmlDocument();
            }

```

So the first query works but the second (nextlink) crashes. It says entity type could not be found. I tried to run the annotations.NextPageLink uri in a browser and that worked. The error message we get is

```
System.AggregateException occurred
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at Enferno.Services.Adlibris.Export.ExportProduct.ExportProductService.GenerateFullFile() in d:\tfs\eCom\Services\Adlibris\Release\1.1\Enferno.Services.Adlibris\Export\ExportProduct\ExportProductService.cs:line 45
       at Enferno.Services.Adlibris.AdlibrisService.ExportProductFull() in d:\tfs\eCom\Services\Adlibris\Release\1.1\Enferno.Services.Adlibris\AdlibrisService.cs:line 63
  InnerException: System.AggregateException
       HResult=-2146233088
       Message=One or more errors occurred.
       Source=mscorlib
       StackTrace:
            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
            at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
            at System.Threading.Tasks.Task`1.get_Result()
            at Simple.OData.Client.FluentClientBase`1.<RectifyColumnSelectionAsync>b__1(Task`1 y)
            at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
            at System.Threading.Tasks.Task.Execute()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at Simple.OData.Client.BoundClient`1.<FindEntriesAsync>d__6.MoveNext()
       InnerException: System.AggregateException
            HResult=-2146233088
            Message=One or more errors occurred.
            Source=mscorlib
            StackTrace:
                 at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
                 at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
                 at System.Threading.Tasks.Task`1.get_Result()
                 at Simple.OData.Client.FluentClientBase`1.<>c__DisplayClass4.<RectifyColumnSelectionAsync>b__3(Task`1 x)
                 at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                 at System.Threading.Tasks.Task.Execute()
            InnerException: Simple.OData.Client.UnresolvableObjectException
                 HResult=-2146233088
                 Message=Entity type FunctionService.GetExportProductFull(clientId=35,skuTypeIdToExclude=14,skuStatusIdToExclude=5) not found
                 Source=Simple.OData.Client.V4.Adapter
                 ObjectName=FunctionService.GetExportProductFull(clientId=35,skuTypeIdToExclude=14,skuStatusIdToExclude=5)
                 StackTrace:
                      at Simple.OData.Client.V4.Adapter.Metadata.GetEntityType(String collectionName)
                      at Simple.OData.Client.V4.Adapter.Metadata.GetEntityCollectionTypeNamespace(String collectionName)
                      at Simple.OData.Client.MetadataBase.GetEntityCollectionQualifiedTypeName(String collectionName)
                      at Simple.OData.Client.V4.Adapter.RequestWriter.<WriteEntryContentAsync>d__8.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                      at Simple.OData.Client.RequestWriterBase.<CreateGetRequestAsync>d__1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                      at Simple.OData.Client.ODataClient.<FindEntriesAsync>d__31.MoveNext()
                 InnerException:

```

**Comment by object** [comment]
Hi,
Can you try the following syntax within the while loop:

items = oDataClient.For&lg;ClientProductSku&gg;()
                        .FindEntriesAsync(annotations.NextPageLink, annotations)
                        .Result;

When using annotations it's sufficient to pass just NextPageLink information, so I wonder if the additional clauses may cause the problem (which is a bug anyway).

**Comment by johanparmar** [comment]
Hi Vagif,
Unfortunately it didn't work. We are experiencing the same issue.

**Comment by object** [comment]
OK, will investigate it. I suppose the service has the same metadata as you mailed me.

**Comment by object** [comment]
I've made some changes in 4.5.4 that probably didn't eliminate the problem but might change the call stack if the error occurs. Could you rerun the test in case of the error provide the following information:

1. Call stack, similar to what you sent earlier.
2. In case the error is sent after the HTTP request is issued, the HTTP request details (URI, content).

Thanks.

**Comment by johanparmar** [comment]
Hi Vagif,
I just tried the function calls and it seems to be working now!?

**Comment by object** [comment]
Good news, I did some changes but wasn't quite sure if it was sufficient. If I don't hear anything from within a few days I will close the issue.

**Comment by johanparmar** [comment]
OK. Cool. Thanks for your assistance
