### ISSUE TITLE
Object of type 'System.DateTimeOffset' cannot be converted to type 'System.DateTime'.

### ISSUE THREAD

**Issue by romangpro** [object/Simple.OData.Client#163]
Entity corresponding to table in database with datetime column
class O{
int Idl
DateTime DateCreated;
}

I have the newest OData V4 WebAPI2 service controller which creates response:
"2015-09-23T21:21:37.42-07:00" (dafault)

            GlobalConfiguration.Configuration.Formatters.JsonFormatter.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Utc;             config.SetTimeZoneInfo(System.TimeZoneInfo.Utc);
"2015-08-24T16:27:55.51Z"

 var v = c.For<O>().FindEntriesAsync().Result.ToList();
Simple.OData.Client FAILS to deserialize the response as a DateTime.

at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject(IDictionary`2 source, Type type, Func`1 instanceFactory, String dynamicPropertiesContainerName, Boolean dynamicObject)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject[T](IDictionary`2 source, String dynamicPropertiesContainerName, Boolean dynamicObject)
   at Simple.OData.Client.FluentClientBase`1.<>c__DisplayClass2.<RectifyColumnSelectionAsync>b__1(IDictionary`2 z)
   at System.Linq.Enumerable.<>c__DisplayClass2`3.<CombineSelectors>b__3(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SimpleODATA_Client.TEST() in

**Comment by romangpro** [comment]
I followed the workaround in http://stackoverflow.com/questions/25189557/how-to-get-web-api-odata-v4-to-use-datetime

I created a UnMapped 2nd DateTimeOffset property, and made the DateTime property "Ignore" in the EDM Model.

I was getting nullreference exceptions, on the DateTimeWrapper, and ended up initializing to default of DateTime.Now.

But, when I supply the class to the generic For, it fails to assign the DateTime to either property.

so I end up having to do this:
            var a = c.For("CAR").FindEntriesAsync().Result.ToList(); //this has the correct dates
            var b = c.For<CAR>().FindEntriesAsync().Result.ToList();
            for (int i = 0; i < a.Count; i++)
            {
                b[i].ModifyDate2 = (DateTimeOffset)a[i]["ModifyDate2"]; // as DateTimeOffset;
                b[i].CreateDate2 = (DateTimeOffset)a[i]["CreateDate2"]; // as DateTimeOffset;
            }
            return b;

**Comment by object** [comment]
Hi,
I am not quite sure why it still failed after you changed types from DateTime to DateTimeOffset - it works in my tests, but I improved the DateTime to DateTimeOffset conversion, so it should work with DateTime without any additional steps in version 4.12 (to be released in a few days).
