### ISSUE TITLE
ExecuteAsEnumerable fails creating default constructor if entity type has static properties

### ISSUE THREAD

**Issue by sixlettervariables** [object/Simple.OData.Client#184]
Given the following entity type:

```csharp
public partial class FooBar
{
   public FooBar()
   {
       // ... no other ctors ...
   }
   //...
}
```

The following has worked just fine:

```csharp
var query = await this.odata.For<FooBar>()
                            .Function("Default.FooBars")
                            .Set(new { param1 = true })
                            .OrderByDescending(x => x.Field)
                            .ExecuteAsEnumerableAsync();
// materialize
return query.ToArray();
```

We just added two static readonly strings to `FooBar`, like so:

```csharp
public partial class FooBar
{
   public static readonly string ABC = "ABC";
   public static readonly string DEF = "DEF";
...
```

And now the above query fails with the following exception:
```
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Simple.OData.Client.Extensions.TypeExtensions.GetDefaultConstructor(Type type)
   at Simple.OData.Client.Extensions.DictionaryExtensions.CreateInstance[T]()
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject(IDictionary`2 source, Type type, Func`1 instanceFactory, String dynamicPropertiesContainerName, Boolean dynamicObject)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject[T](IDictionary`2 source, String dynamicPropertiesContainerName, Boolean dynamicObject)
   at Simple.OData.Client.FluentClientBase`1.<>c__DisplayClass2.<RectifyColumnSelectionAsync>b__1(IDictionary`2 z)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at A.B.Baz.<GetFooBarAsync>d__42.MoveNext() in X:\Foo\Bar.cs:line 999999
```

I believe this is because [`DeclaredConstructors`](https://github.com/object/Simple.OData.Client/blob/3eb84af1aa7d0234a1e87e5f004202e82cbd091f/Simple.OData.Client.Core/Extensions/TypeExtensions.cs#L192) includes the static constructor:

```csharp
        public static ConstructorInfo GetDefaultConstructor(this Type type)
        {
            return type.GetTypeInfo().DeclaredConstructors.SingleOrDefault(x => x.GetParameters().Length == 0);
        }
```

**Comment by sixlettervariables** [comment]
It looks like the regression is for .Net 4.5+ with the switch to `GetTypeInfo()`. Prior to .Net 4.5 the code explicitly asked for only instance fields, properties, methods, and constructors. Now any declared one is considered.

[My attempt at a patch can be seen on my fork](https://github.com/sixlettervariables/Simple.OData.Client/pull/1), not a PR as I've not cleaned it up or tested it well enough to be sure it fixes the problem completely.

**Comment by sixlettervariables** [comment]
Would you like a PR for this?

**Comment by object** [comment]
Oh yes, with pleasure. I am sorry for not being able to look into this myself due to other prioritized stuff, but if you have a resolution ready, I would very much like to receive a PR from you.
