### ISSUE TITLE
Cannot access O365 Endpoints due to failure to handle Metadata

### ISSUE THREAD

**Issue by ravensorb** [object/Simple.OData.Client#225]
I am trying to access on of the endpoints in O365 (/portals/hub/_api/VideoService).  This is in a PCL class library that is being used inside a Windows Mobile 10 application.

```c#
var _client = new Simple.OData.Client.ODataClient(new Simple.OData.Client.ODataClientSettings {
				BaseUri = new Uri("http://MYSITEINSTANCE.sharepoint.com/portals/hub/_api/VideoService"),
				IgnoreResourceNotFoundException = true,
				MetadataDocument = "https://MYSITEINSTANCE.sharepoint.com/portals/hub/_api/$metadata",
				PayloadFormat = Simple.OData.Client.ODataPayloadFormat.Json,
				IgnoreUnmappedProperties = true, 
				RenewHttpConnection = false, 
				BeforeRequest = (message) => {
					var tokenManager = Resolver.Resolve<ITokenManager>();
					message.Headers.TryAddWithoutValidation("Authorization", "bearer " + tokenManager.Token);
				},
				OnTrace = (a, p) => {
					System.Diagnostics.Debug.WriteLine(a, p);
					Serilog.Log.Debug(a, p); 
				},
				AfterResponse = (responseMessage) => {
					System.Diagnostics.Debug.WriteLine(responseMessage.StatusCode);
					Serilog.Log.Debug("Status Code: {0}", responseMessage.StatusCode);
				}
			});
```

Then I make a call like this

```c#
var result = await _client.For<Channel>("Channels").FindEntriesAsync();`
```

And I get the following error when trying to access anything

```c#
{"Data at the root level is invalid. Line 1, position 1."}`
```

```c#
"   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Simple.OData.Client.AdapterFactory.GetMetadataProtocolVersion(String metadataString)\r\n   at Simple.OData.Client.AdapterFactory.CreateAdapter(String metadataString)
   at Simple.OData.Client.Session.<ResolveAdapterAsync>d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Simple.OData.Client.ODataClient.<FindEntriesAsync>d__ba.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Simple.OData.Client.FluentClientBase`1.<RectifyColumnSelectionAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AvanadeTube.Services.O365ClientService.<LoadChannels>d__2.MoveNext()
-- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AvanadeTube.ViewModels.VideoChannelViewModel.<RefreshChannels>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AvanadeTube.App.<LoginEventsViewModel_Authenticated>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()"
```

**Comment by ravensorb** [comment]
Ok, from what I can tell there are a few things that are not working in this area

- No support for json metadata (looks like it is hard coded to use xml)
- No way of tracing the Loading of Metadata (BeforeRequest and CreateMessageHandler not used during this process)

If I take the XML returned from O365 and load it in a XmlReader object, it works so I think there might be an issue in how Simple.OData.Client is handling the resulting content from the metadata call in the ODataRequest class.  Possibly it is loading it as UTF-16 rather than UTF-8?

**Comment by ravensorb** [comment]
One more update -- if I switch over to a basic HttpClient call and set the headers, everything does seem to work correctly.

**Comment by object** [comment]
Hi,
Sorry for the late response. AFAIK support for JSON metadata is still not officially released (see the draft https://www.oasis-open.org/committees/document.php?document_id=56653) even though some OData services offer JSON metadata. So unfortunately until it will be supported by Microsoft ODataLib (which I am using at a lower level) you will have to configure metadata requests to be replied as XML.

**Comment by ravensorb** [comment]
I can understand about not supporting json for metadata right now. The bigger issue is that it is failing when trying to parse the XML formatted result returned by the O365 API.  I think this is being caused by a encoding issue.

**Comment by object** [comment]
If you think this is caused by encoding, can you send me (perhaps to vagif.abilov at gmail) the result that causes the exception? I have never received issues related to encoding before.
