### ISSUE TITLE
Using Simple.OData.Client typeless syntax to call action that accepts ComplexType parameter

### ISSUE THREAD

**Issue by apngithub** [object/Simple.OData.Client#231]
Hi,

I have an OData service that exposes an action whose metadata looks like this:

```
        <Action Name="DoMyAction">
            <Parameter Name="entityView" Type="EntityViews.EntityView" />
            <ReturnType Type="Commands.Command" />
        </Action>
```

where the EntityView type is:

```
        <ComplexType Name="EntityView" BaseType="MyCompany.Core.Model">
            <Property Name="EntityId" Type="Edm.String" />
            <Property Name="ItemId" Type="Edm.String" />
        </ComplexType>
```

I can successfully call this action through POSTMAN. The captured request looks like this:

PUT http://localhost:5000/api/DoMyAction() HTTP/1.1
Host: localhost:5000
Connection: keep-alive
Content-Length: 86
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
IpAddress: 1.0.0.0
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 767a2cad-673f-52fa-3454-5e18cc6c4816
Accept: _/_
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

{
  "EntityId": "{6728db04-aae8-487e-a763-10b9b1419bd2}",
  "ItemId": "123"
}

Can you please tell me what the equivalent typeless syntax using the client should be? I've tried the following:

```
        var result = Task.Run(async () =>
        {
            var client = new ODataClient(GetClientSettings());
            var actionResponse = await client.Unbound<IDictionary<string, object>>().Action("DoMyAction").Set(new { EntityId = entityId, ItemId = itemId }).ExecuteAsSingleAsync();
            return actionResponse;
        }).GetAwaiter().GetResult();
```

but I got the following exception

[UnresolvableObjectException: Parameter [EntityId] not found for action [DoMyAction]]

I would have thought that the anonymous object as constructed would serialize the same way as I displayed in the above POSTMAN example.

Any help you could give me would be greatly appreciated. I'm somewhat new to this library.

I'm using version 4.15.0.

Thanks.

**Comment by object** [comment]
Hi,

Can you try the following:

var value = new { EntityId = entityId, ItemId = itemId };
var actionResponse = await client.Unbound<IDictionary<string, object>>().Action("DoMyAction").Set(new { entityView = value }).ExecuteAsSingleAsync();

Simple.OData.Client tries to match the anonymous object properties with the ones defined in metadata. And in your service it's "entityView" that is defined.

**Comment by michalhainc** [comment]
Hi so I ran into (what I believe is) the same problem as you were solving in this thread. 

My code: 
```c#
        _client
	.Unbound<Dictionary<string,object>>()
	.Action("GetConnectionsBetweenElements")
	.Set(new
	{
	  elements = new { src = rowElement.ElementGuid },
	  serializationDepth = 2
	})
	.ExecuteAsEnumerableAsync();
```
EDM metadata for the action: 

```xml

<Action Name="GetConnectionsBetweenElements">
  <Parameter Name="elements" Type="Collection(MyUmlRest.Models.ConnectorQueryModel)" Nullable="false" />
  <Parameter Name="serializationDepth" Type="Edm.Int32" />
  <Parameter Name="includedConnectorUmlTypes" Type="Collection(LL.MDE.DataModels.MyUml.Uml2.AllUmlTypes)" />
  <Parameter Name="includedConnectorStereotypes" Type="Collection(Edm.String)" Unicode="false" />
  <ReturnType Type="Collection(MyUmlRest.Models.ModelObject)" />
</Action>

<ComplexType Name="ConnectorQueryModel">
  <Property Name="src" Type="Edm.String" />
  <Property Name="dst" Type="Edm.String" />
</ComplexType>
```

I am getting exception: 

```
System.NullReferenceException: Object reference not set to an instance of an object.
at Simple.OData.Client.V4.Adapter.RequestWriter.<WriteOperationParameterAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Simple.OData.Client.V4.Adapter.RequestWriter.<WriteActionContentAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Simple.OData.Client.RequestWriterBase.<CreateActionRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Simple.OData.Client.ODataClient.<ExecuteActionAsync>d__153.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Simple.OData.Client.ODataClient.<ExecuteAsEnumerableAsync>d__106.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Simple.OData.Client.FluentClientBase`1.<RectifyColumnSelectionAsync>d__34.MoveNext()
```

Anyway I can call the action successfully via raw http request like this:

```
POST http://localhost/MyUmlRest/GetConnectionsBetweenElements?$format=application/json;odata.metadata=none HTTP/1.1
Host: localhost
Connection: keep-alive
Content-Length: 179
Postman-Token: dc28f398-411c-045b-0f59-ead4c4ce02c7
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: sk-SK,sk;q=0.8,cs;q=0.6,en-US;q=0.4,en;q=0.2

{ 
	"elements": [ 
		{ "src":"{B97EF8FD-C99D-4513-AA08-86AEB346622C}" }
		],
	"serializationDepth": 2
}
```

**Comment by object** [comment]
Thank you for the bug report. I will investigate this.
