### ISSUE TITLE
Insert with $expand

### ISSUE THREAD

**Issue by zivillian** [object/Simple.OData.Client#295]
I have an unusual request, which uses $expand on a navigation property while inserting or updating entities (to prevent an additional roundtrip after modifying an entity). This was added to the OData Spec [(ODATA-614)](https://issues.oasis-open.org/browse/ODATA-614) and is already supported by WebAPI ODataController ([ReturnContent Property](https://msdn.microsoft.com/en-us/library/microsoft.odata.core.odatapreferenceheader.returncontent(v=vs.113).aspx), [example](https://github.com/OData/WebApi/issues/356)).

For update via PUT this is already supported by the Simple.OData.Client, but when using $expand on an insert it throws an exception in [ODataClient.Internals.cs](https://github.com/object/Simple.OData.Client/blob/73287ccf3a992d2eec989c7867849497bc92aa22/Simple.OData.Client.Core/ODataClient.Internals.cs#L28):
```
Simple.OData.Client.UnresolvableObjectException
Entity type [People?$expand=Trips] not found
   at Simple.OData.Client.V4.Adapter.Metadata.GetEntityType(String collectionName)
   at Simple.OData.Client.V4.Adapter.Metadata.GetDeclaredKeyPropertyNames(String collectionName) 
   at Simple.OData.Client.ODataClient.<ExecuteInsertEntryAsync>d__12d.MoveNext()
```

Here's the unit test, which I used to create the above Exception:

```
[Fact]
public async Task InsertPersonWithExpand()
{
   var person = await _client
		.For<Person>()
		.Set(new
		{
			UserName = "gregorsamsa",
			FirstName = "Gregor",
			LastName = "Samsa",
		})
		.Expand(x=>x.Trips)
		.InsertEntryAsync();
}
```

I've created a [patch](https://gist.github.com/zivillian/29fa3d25012def9e0f14edde02f75124) which fixes the exception for this test, but I'm not sure, if this will work for all response types.

**Comment by object** [comment]
Thank you for the initiative. I will check this out and embed it into the library.
