### ISSUE TITLE
Getting Exception System.IO.FileNotFoundException for Android

### ISSUE THREAD

**Issue by RajeshwariML** [object/Simple.OData.Client#343]
Hi,

I was getting the error assembly reference not loaded so i used this  V3Adapter.Reference(); in the App() Xamarin project.

Now i am getting compilation error by using that. 

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Microsoft.Data.OData, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Microsoft.Data.OData.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()	SampleApp.Droid

**Comment by crippledfaith** [comment]
I am facing the same problem. Please help.
http://stackoverflow.com/questions/41133382/simple-odata-client-inside-potable-class-library

**Comment by object** [comment]
It's not easy to figure out what can cause such issue without looking at the actual content of the folders, but usually this is due to version mismatch of some DLLs. Did you check what version of Microsoft.Data.OData.dll is present in the bin folder? Did you try to configure assemblyBinding in app.config (configuration/runtime/assemblyBinding section)?
