### ISSUE TITLE
Function using array as Parameter

### ISSUE THREAD

**Issue by matteoleggieri** [object/Simple.OData.Client#348]
Hello,
I set up my OData service with a function declared as below:

WebApiConfig.cs
- builder.EntitySet<Domain>("Domains");
- builder.Function("ListDomains").ReturnsCollectionFromEntitySet<Domain>("Domains").CollectionParameter<string>("ListIdentifiers");

DomainsController
- [HttpGet]
- [ODataRoute("ListDomains(ListIdentifiers={listIdentifiers})")]
- public IHttpActionResult ListDomains([FromODataUri] IEnumerable<string> listIdentifiers)
- Implementation which return an IHttpActionResult with a collection of items "Domain"

I tried with a RESTClient (Google) using following GET request
- http://hostname:port/ListDomains(ListIdentifiers=['identifier1','identifier2'])

and it works fine with a JSON response with a collection of Domain elements.

But when I try to do the request with Simple.OData.Client as described below
- var result = await client.Unbound<Domain>().Function("ListDomains").Set(new { ListIdentifiers = new string[] { "identifier1","identifier2" } }).ExecuteAsEnumerableAsync();

it fails with the Exception
- !BolLG!The type 'System.String[]' is not supported when converting to a URI literal. Ploc Pl!

I tried to Set directly the string array in the ".Set" clause -->".Set( new string[] { "identifier1","identifier2" })" and in this case the Exception is
- Mismatch in number of parameters (really the exception is in Italian, I translated it so I think is something similar).

What's wrong? Does this mean that Arrays and Complex Object (I tried with them too obtaining the same Exception) are not supported by Client?

Thanks for the support.
Matteo.

**Comment by object** [comment]
Hi,

Can you send me your service metadata file to vagif.abilov at gmail.com? The whole file or just the definition of this function? I'd like to write a test for this case.

**Comment by object** [comment]
Can you please verify this with the version 4.25.0? It contains a possible fix for this problem.

**Comment by matteoleggieri** [comment]
Hi Mr. Vagif,
Actually I can't test the version 4.25.0 because I'm out of the office. I will check it as soon as possibile.
Anyhow I have just sent an email with the information requested in the previous answer.
Thanks for the support.

**Comment by mkmk89** [comment]
Hi, I can reproduce the same bug:

```
            Dictionary<string, object> subParameters = new Dictionary<string, object>();
            subParameters.Add("@odata.id", new Guid("B5262003-769C-E711-80F8-C4346BAC4304"));
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("Target", subParameters);
            parameters.Add("FieldName", "new_rollup");
            client2.Unbound().Function("CalculateRollupField").Set(parameters).ExecuteAsEnumerableAsync().Wait();
```

throws: 
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\macie\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 82

Inner Exception 1:
ODataException: The type 'System.Collections.Generic.KeyValuePair`2[System.String,System.Object]' is not supported when converting to a URI literal.

Thanks for support!
