### ISSUE TITLE
client call endpoint

### ISSUE THREAD

**Issue by Makison** [object/Simple.OData.Client#382]
Hi, I'm using Client.V4
for entities with correspondig entity names like 
                <EntitySet Name="products" EntityType="WStore.Data.EDModel.Product">
it works as expected 

But when I tried to switch to dto objects
          <EntitySet Name="manufacturers" EntityType="WStore.Dto.ManufacturerDto" />

client makes call by EntityType name instead of the EntitySet name
http://localhost:8000/odata/ManufacturerDto?$skip=0&$top=10&$count=true
expected call
http://localhost:8000/odata/manufacturers?$skip=0&$top=10&$count=true

as a result service returns no such endpoint error

Full edm metada 
[metadata.txt](https://github.com/object/Simple.OData.Client/files/785055/metadata.txt)

Thanks

**Comment by object** [comment]
Hi,
How does you client code look?

**Comment by Makison** [comment]
var settings = new ODataClientSettings(new Uri(hostUri))
            {
                UnqualifiedNameCall = true,
            };

            if (logTrace)
            {
                settings.IgnoreResourceNotFoundException = true;
                settings.TraceFilter = ODataTrace.All;
                settings.OnTrace = (x, y) => Log.Info(string.Format(x, y));
            }
           
            if (!string.IsNullOrWhiteSpace(authToken))
            {
                settings.BeforeRequest = (message) =>
                {
                    message.Headers.TryAddWithoutValidation("Authorization", "bearer " + authToken);
                };
            }

            client = new ODataClient(settings);
            var annotations = new ODataFeedAnnotations();
            var entities = await client.For<ManufacturerDto>()
                .Filter(e => e.IsActive == true)
                .FindEntriesAsync(annotations);

To make it work I had to specify explicitly
            var entities = await client.For<ManufacturerDto>("manufacturers")
                .Filter(e => e.IsActive == true)
                .FindEntriesAsync(annotations);

**Comment by object** [comment]
But isn't it expected? How else the library would figure out that ManufacturerDto corresponds to an entityt set "manufacturers"?

**Comment by Makison** [comment]
it's specified in the metadata
 <EntitySet Name="manufacturers" EntityType="WStore.Dto.ManufacturerDto" />

**Comment by object** [comment]
Oh I see, then it's strange. I will look into it.

**Comment by zouzouoz** [comment]
Hi
I seem to be having a problem with above code.  I get the List however they are returned in the "non-public members" and therefore I am not able to access the results.  I am not sure what I am doing wrong here.
         var annotations = new ODataFeedAnnotations();
         var userSetingsList = client
                .For<UserSettings> ("usersettingscollection")
                .FindEntriesAsync(annotations)
                .Result;

            foreach (var UserSettings_Item in userSetingsList)
            {
                //DoSomething;
            }
So when I execute the foreach it is not mapping back although it is trying to loop through all the 388 returned records.  I would really appreciate your feedback and assistance.  I have also tried the above code without the annotations but same results.

Thanks.

Attachments: userSettingsList.JPG, userSettings_Item.JPG
![usersettingslist](https://user-images.githubusercontent.com/39354144/47947253-5e38a500-df6d-11e8-92b9-6e44a8cd8ebc.JPG)
![usersettings_item](https://user-images.githubusercontent.com/39354144/47947254-60026880-df6d-11e8-8793-3e03ee2ba914.JPG)

**Comment by weitzhandler** [comment]
I have the same issue.
This didn't work for me.

> To make it work I had to specify explicitly
> 
>         var entities = await client.For<ManufacturerDto>("manufacturers")
>             .FindEntriesAsync(annotations);

Is there an extensibility point when deserializing the entities or when deciding which type we're looking for?

In my scenario, the controller chooses when to return a DTO. When I call `await _ODataClient.For<Contact>().FindEntriesAsync();`, if the resulted entity is a DTO I get the following exception:

`Microsoft.OData.ODataException: 'The context URL 'https://test.myproject.com/api/$metadata#Contacts/MyProject.Data.ContactDto' is invalid.'`

StackTrace:
>at Microsoft.OData.JsonLight.ODataJsonLightContextUriParser.ParseContextUriFragment(String fragment, Func`3 clientCustomTypeResolver, Boolean throwIfMetadataConflict, Boolean& isUndeclared)
   at Microsoft.OData.JsonLight.ODataJsonLightContextUriParser.ParseContextUri(ODataPayloadKind expectedPayloadKind, Func`3 clientCustomTypeResolver, Boolean throwIfMetadataConflict)
   at Microsoft.OData.JsonLight.ODataJsonLightContextUriParser.Parse(IEdmModel model, String contextUriFromPayload, ODataPayloadKind payloadKind, Func`3 clientCustomTypeResolver, Boolean needParseFragment, Boolean throwIfMetadataConflict)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart(ODataPayloadKind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.ReadSynchronously()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.OData.ODataReaderCore.Read()
   at Simple.OData.Client.V4.Adapter.ResponseReader.ReadResponse(ODataReader odataReader, IODataResponseMessageAsync responseMessage) in D:\Users\Shimmy\Source\Repos\Simple.OData.Client\src\Simple.OData.Client.V4.Adapter\ResponseReader.cs:line 148

**Comment by weitzhandler** [comment]
Hi,

In my approach I did the opposite than what the post author did, I combined the `Contact` and `ContactDto` routes in one controller.
I'm wondering if there is any extensibility point where SOC lets us decide how we want to map the entity data to object, so instead of resolving to `Contact` it does to `ContactDto` (for example if I use `.For<Contact>().As<ContactDto>()`, or `.For<Contact>().ConvertTo<ContactDto>(dtoConverter)` or anything like that, that allows composing any object from the raw data from server, by explicitly specifying the desired type and mapper/converter/manual.

I made a [*repro*](https://github.com/weitzhandler/ODataDtoRepro) project that demonstrates this.

**Comment by weitzhandler** [comment]
Hi,

In my approach I did the opposite than what the post author did, I combined the `Contact` and `ContactDto` routes in one controller.
I'm wondering if there is any extensibility point where SOC lets us decide how we want to map the entity data to object, so instead of resolving to `Contact` it does to `ContactDto` (for example if I use `.For<Contact>().As<ContactDto>()`, or `.For<Contact>().ConvertTo<ContactDto>(dtoConverter)` or anything like that, that allows composing any object from the raw data from server, by explicitly specifying the desired type and mapper/converter/manual.

I made a [**repro**](http://bit.ly/31XT2R4) project that demonstrates this.

**Comment by weitzhandler** [comment]
If we're querying `For<Contact>()` and the server returns JSON like this:
```json
{ 
   "@odata.context":"https://localhost:54687/api/$metadata#Contacts/ODataDtoRepro.Models.ContactDto",
   "value":[ 
      { 
         "@odata.type":"#ODataDtoRepro.Models.ContactDto",
         "Id":1,
         "DisplayName":"John Doe"
      },
      { 
         "@odata.type":"#ODataDtoRepro.Models.ContactDto",
         "Id":2,
         "DisplayName":"Microsoft"
      }
   ]
}      
```
SOC parses the type `ContactDto` from it automatically.

At least there should be a converter overload like
`RegisterTypeConverter<TQuery, TResult>(Func<IDictionary<string, object>, TResult> converter)` or `RegisterTypeConverter<TQuery>(Func<Type /*edmType*/, IDictionary<string, object>, object> converter)`, so we can explicitly tell it to.

Check out my other [**repro branch**](https://github.com/weitzhandler/ODataDtoRepro/tree/base-class) which experiments with that.

**Comment by weitzhandler** [comment]
Hopefully I can implement that myself, what I'm intending to do, is when the JSON is received, if it has a type specified, attach that type as the desired type.
Maybe we should add an extension method on `IBountClient<T>`, let's say `AsResult` or you name it, that tells SOC and the CLR which specific type we're going to get from the server, which might be different than the original requested type, then we won't need a converter.
But anyway, the converter should have an incoming argument that tell us the JSON type if any.

**Comment by weitzhandler** [comment]
Posted [this](https://stackoverflow.com/questions/58278116/dtos-with-simple-odata-client) bounty question on SO, would appreciate any help.

**Comment by TheCakeMonster** [comment]
Yes, I've encountered this problem as well. Hopefully at some point one of us will be able to find and fix it!
