### ISSUE TITLE
Allow use of Simple Odata CLient with existing HttpClient

### ISSUE THREAD

**Issue by NetTecture** [object/Simple.OData.Client#502]
No url, no authentication - just use the existing HttpClient

Reason:

dotnetcore test frameworks allow the instaltiation of a website with a WebApplicationFactory that then can be asked for a HttpClient

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1

This means no dealing with local URL's etc. jsut to test an endpoint in an integraiton test.

**Comment by object** [comment]
Let me think about, whether this is possible (or easy) to achieve.

**Comment by NetTecture** [comment]
To tell you the truth, this just got pushed to a high prio for me.

I am writing a new API that is supposed to use Simple Odata Client and OAuth. Both servers are part of the API.

To integration test, i start them both in process with the new dotnet core integration test framework.

I am totally unable to get Simple Odata Client to connect.

This works:

            var bearerToken = TestSetup.OAuth.access_token;
            var client = TestSetup.WebFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", bearerToken);
            var response = await client.GetAsync("Building");

(TestSetup being a static class - as yo ucan see, CreateClient)

This does not:

            var apiClient = new ODataClient(TestSetup.ClientSettings);
            var x = ODataDynamic.Expression;
            var data = await apiClient
                .For<OdataApi.Building>("Building")
                .Top(100)
                .FindEntriesAsync();

The exception....

Message: Test method Tests.Api.Odata.Web.Controllers.BuildingTests.List threw exception: 
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it


Dunny thing is that I just can not get connection parameters our of the generated client. Clients to both endpoints show https://localhost as absolute base url. There isa handler attached, but i cna not easily copy that given i have zero control over the httpclients.

As such, I will not be able to use Simple Odata Client in the integration tests - which is seriously bad because it means I can not really test them end to end with the same client technology that will be used by half of the userbase (the others using something javascript based).

**Comment by phatcher** [comment]
@NetTecture 

The error you are reporting is typically when the server endpoint isn't listening, so are you spinning up a copy of the server as well in your test setup or is expected that this is running at a well-known location?

I'd suggest checking the port that you are talking to as by default NetCore will spin up servers on port 5000 rather than port 80

**Comment by NetTecture** [comment]
This is the point - I do not know. See, I am SUPPOSED to use the ClientFactory of the new integration test framework. I can not, because simple odata client does not work with injected clients.

So, I ask the generated httpclient about it's information, and they all have the same base url (http://localhost). There also is a handler attached that I can not access and again can not inject.

I am sure there is some magic with paths, but it is hidden. New test framework, nicely assuming everyone jumps to integrate.

I wouldl ove to - I would love to give both, our new API and Simple Odata Client a hard beating using the integration tests. Stuck on taht part now.

**Comment by object** [comment]
I need to better understand premises of that test framework, but thinking of workaround: Simple.OData.Client basically performs 4 steps for the given C# code:
1. Generates OData URI
2. Generates HTTP payload for HTTP POSTs
3. Run request using HttpClient
4. Parsers HTTP response converting it to C# POCO types

Your code examples doesn't generate POST payload, you only need to generate OData URI which can be done using GetCommandTextAsync. From there you can use HttpClient, you will just need to parse JSON response message, but this is also doable using JSON.NET.

**Comment by NetTecture** [comment]
The problem with that approach is that you give up on most of the client side API. Which is fine as a short term workaround, but definitely not wanted long term - I want test writers to be able to test the whole codebase of odata client, also because this allows copy/pasting queries that fail.

Really need to work with something like.... basically not putting a base URL into Simple Odata CLient, but putting a HttpClient in. That way it can be initialized once (during setup) and just be kept around.

**Comment by NetTecture** [comment]
Sounds likea decent solution to me. The HttpCLient will have the base url preconfigured (the one you can enter now) and all sub-url's are generated by you. Possibly allow a second path part parameter so I can so

new ..... (existingHttpClient, "/odata/") and it then adds "/odata" to the path. Then I can ask the factory from the dotnet core testing framework to give me a HttpClient and it gets used.

**Comment by object** [comment]
I see. Let me experiment a little.

**Comment by object** [comment]
@NetTecture I created an experimental branch called custom-http-client where ODataClientSettings are extended with a new property ExternalHttpClient. You can set it to your instance and ODataClient will use it instead of creating its own. Can you test this branch with your scenario (there is no NuGet package, just build it from sources using that branch).

**Comment by NetTecture** [comment]
Got it. Does not work ;) Not sure what I do wrong.

My setup, centrally:

            var settings = new ODataClientSettings()
            {
                ExternalHttpClient = WebFactory.CreateClient(),
            };
            settings.BeforeRequest += delegate (HttpRequestMessage message)
            {
                message.Headers.Add("Authorization", "Bearer " + OAuth.access_token);
            };
             ClientSettings = settings;

Then the test:

            ODataClient c = new ODataClient(TestSetup.ClientSettings);
            var s = await c
                .For<OdataApi.Building>()
                .Top(5)
                .FindEntriesAsync();

Error:

Message: Test method Tests.Api.Odata.Web.Controllers.BuildingTests.List threw exception: 
System.InvalidOperationException: Unable to create client session with no URI specified.

Stack trace:

Result StackTrace:	
at Simple.OData.Client.Session..ctor(ODataClientSettings settings) in C:\Work\Simple.OData.Client\src\Simple.OData.Client.Core\Session.cs:line 29
   at Simple.OData.Client.Session.FromSettings(ODataClientSettings settings) in C:\Work\Simple.OData.Client\src\Simple.OData.Client.Core\Session.cs:line 142
   at Simple.OData.Client.ODataClient..ctor(ODataClientSettings settings) in C:\Work\Simple.OData.Client\src\Simple.OData.Client.Core\ODataClient.cs:line 47
   at Tests.Api.Odata.Web.Controllers.BuildingTests.List() in C:\Work\OBB\Source.Backend\Tests.Api.Odata.Web\Controllers\BuildingTests.cs:line 22

Note that the created HttpCLient acutally does already know it'sproject base URL somehow (that is the magic - it only shows http://localhost).

**Comment by object** [comment]
Let me check it.

**Comment by phatcher** [comment]
@object Can I also suggest we have it as an optional constructor parameter - this will then play nicely with the NET Core HttpClientFactory bits

**Comment by object** [comment]
@NetTecture I wrote a small test that works fine:

```
            var client = new ODataClient(new ODataClientSettings(_serviceUri)
            {
                ExternalHttpClient = new HttpClient(),
            });

            var person = await client
                .For<Person>()
                .Key("russellwhyte")
                .FindEntryAsync();

            Assert.Equal("russellwhyte", person.UserName);

```

I suggest you debug your code to find out what might be the reason for failure. I don't see any errors in the library right now.

**Comment by object** [comment]
@phatcher So you are saying that having it in ODataClientSettings will not help when using with HttpClientFactory? Won't it be possible to send ODataClientSettings with ExternalHttpClient?

Can you give me a code example of how it will be used if HttpClient is sent via constructor?

If only the latter works, perhaps we should _only_ provide it with constructor overload, not via ODataClientSettings? Wherever possible I want to have a single way of specifying setup option. Unless of course there are good reasons of having it in two places.

**Comment by NetTecture** [comment]
@object It is actually quite simple. I don't HAVE a _serviceUri.

The httpClient that I inject is preconfigured with the base URL of the website it is starting. It already has a BaseAddress.

I tried var settings = new ODataClientSettings("/")

But that does not work either.

**Comment by phatcher** [comment]
@object What you typically do is wire the HttpClient up with a well-known base address, see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1 for the full details, but I believe the most appropriate one is the named client so you can do something like this...
```
services.AddHttpClient<ODataClientSettings>(c =>
{
    c.BaseAddress = new Uri("https://api.github.com/");
    c.DefaultRequestHeaders.Add("Accept", "application/vnd.github.v3+json");
    c.DefaultRequestHeaders.Add("User-Agent", "HttpClientFactory-Sample");
});
```
The built in DI is a bit weak in that it doesn't support named instances so we will have to play with what happens with multiple OData endpoints, may be a trivial sub-typing of Settings/Client so that it plays nice with the DI

**Comment by object** [comment]
@NetTecture Try now.

**Comment by object** [comment]
@phatcher but what happens on this call?

`services.AddHttpClient<ODataClientSettings>`

ODataClientSettings has a property ExternalHttpClient. Or you suggest adding a new constructor to ODataClientSettings, not ODataClient?

**Comment by NetTecture** [comment]
Works. No error and I actually get data ;) Ah, so nice. Now I can write integrated unit tests that test full functionality of Odata without writing manual URL's ;) THAAAAANNNNKS ;)

When can I expect this to hit nuget?

**Comment by object** [comment]
As you see in this thread, we are discussing with @phatcher what would be the best API syntax: either have it as ExternalHttpClient property or a new constructor overload. Once we will figure it out, there will be a new package soon.

**Comment by NetTecture** [comment]
nice. I think a constructor would be amazing - it is "easier" and it allows DI.

THAT SAID: you should definitely allow to add a parth part in settings or constructor, in case the api lives ina folder. RIght now it always goes against / - which is fine for me, but simpler projects (where the API is not a separate visual studio project but in the same code as the website) may need to access a folder.

**Comment by object** [comment]
@NetTecture you mean ODataClientSettings constructor?

Regarding the second suggestion, can you give an example of how you would expect partial path to work?

**Comment by NetTecture** [comment]
Sure, It is actually quite simple.

Right now:
* Api is based on the project (i.e. Controlelrs folder in the project).
* The injected HttpClient is configured to access the root of the web project.

I.e. HttpClient shows to / of wherever the projcet is.

COmplex case:
* The api is based in an AREA of the project. i.e. The area is "api".
* The injected HttpClient is configured to access the root of the web project, regardless where it is.

If you use a constructor, then it could work like this:

Current: new ODataCLient (string url)

Alternative: new OdataClient (generatedHttpClient, string relativeUrl)

example:
var client = WebFactory.CreateClient()
var odataClient = new OdataClient (client, "/api");

result: Odata is assumed to be in a folder "api" in wherever the httpclient points to.

**Comment by object** [comment]
I see. Thank you for the clarification. So what advantage would you get if ODataClient would take an external HttpClient in a constructor rather than ODataClientSettings? These settings provide lots of customization points so people often create an instance of ODataClientSettings and pass it to ODataClient constructor. What would be simpler for you if you can send HttpClient to ODataClient ctor and not as ODataClientSettings.ExternalHttpClient? Would it make sense to keep ExternalHttpClient if there was a ctor support?

**Comment by phatcher** [comment]
@object Yes I use ODataClient a lot in web sites e.g. I have an MVC site which talks to the WebApi site using OData, so DI is very useful.

Don't mind if we inject the HttpClient into ODataClientSettings or ODataClient, but I take @NetTecture point regarding a subsidiary url, though the potential issue with this is sharing the endpoint with other users and how that might interact with the HttpMessageHandler etc. It might be cleaner to require a "pure" HttpClient configured with the correct url, probably need some testing.

One rationale for putting the HttpClient onto ODataClientSettings is that it should provide a clean entry point for centralising the creation of the HttpClient i.e. we have either been given it and if not create it - this would potentially minimise the creation of HttpClient instances, so they only get released on destruction of the ODataClientSettings if they have been created internally.

One nice thing we would get via DI of either is easy introduction of Polly policies so transient errors could be handled automatically

**Comment by NetTecture** [comment]
@phatcher Again, the problem when using (the new dotnetcore 2.1 test framework) is that you have no easy and clean way to get the actual base URL. There is a whole logic hidden that determines it based on project name and some other stuff and it is not exposed. You ask the factory for a HttpClient, that is it - that is how the whole thing started. So, it is either live with what you ahve as HttpClient from a factory, or not use the new integrated test framework. In this case, adding folders to the request path is a requirement for cases where the api is an area. Now, if you can find a way to live with a new clean httpClient - be my guest. But do not expect that tocome to an easy conclusion before the tricket in that regard to MS is fixed (I opened one asking them that the WebFactory please exposes the URL of the generatd site ina property).

**Comment by object** [comment]
OK. So what if we keep existing ODataClient constructors untouched, but extend ODataClientSettings ctors, to they will contain:

ODataClientSettings() // existing
ODataClientSettings(string baseUri, ICredentials credentials = null) // existing
ODataClientSettings(Uri baseUri, ICredentials credentials = null) // existing
ODataClientSettings(HttpClient httpClient, Uri relativeUri = null, ICredentials credentials = null) // new

and in addition keep ExternalHttpClient (is there better name for it?)

What do you think?

**Comment by phatcher** [comment]
@object Looks good, but I'd call it HttpClient and make it read-only, and later on we can move the HttpClient creation into ODataClientSettings and minimize the allocations.

**Comment by object** [comment]
Good point @phatcher

**Comment by object** [comment]
I can't make the property readonly. Needs to be converted to a field. Not sure it's worth it.

**Comment by phatcher** [comment]
You can do

`public HttpClient { get; private set; }`

**Comment by object** [comment]
I also plan to make obsolete ODataClientSettings(string baseUri, ICredentials credentials = null), so people will use Uri instead.

**Comment by object** [comment]
Released version 5.4 with this improvement.

**Comment by weitzhandler** [comment]
What's the recommended life-cycle of an `ODataClient`?
Is it supposed to be a singleton? If the answer is yes, since we want the `HttpClient` lifetime to be determined and disposed of by the `IHttpClientFactory`, it appears to be tunnelling down to `HttpConnection`, where the `HttpClient` is created.
I'm curious if we can use [`AddHttpClient<MyODataClientSettings>`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=aspnetcore-2.2), which since `ODataClientSettings` has a `HttpClient` accepting constructor might just work (not sure how DI will cope with the optional params).

**Comment by weitzhandler** [comment]
BTW, there is a good example [here](https://github.com/simple-odata-client/Simple.OData.Client/issues/416#issuecomment-436334552).

**Comment by weitzhandler** [comment]
@phatcher, thanks for your examples.

We should register the `ODataClient` itself as singleton so the metadata etc. is cached, shouldn't we?

But we'd want the `ODataClientSettings` (with an injected `HttpClient`) to be transient or at most scoped, not singleton.
One of the main purposes of the `IHttpClientFactory` is to renew it because otherwise it doesn't respect DNS changes (https://github.com/dotnet/corefx/issues/11224). The current implementation wouldn't allow that, because it retains the `HttpClient`'s life to the `ODataClient` one's.

I think it would be worth introducing an `IODataSettingsFactory` interface, perhaps with an accompanying `DefaultODataSettingsFactory` that has both a parameterless and an `ODataClientSettings` accepting constructor, maybe an `HttpClient` one as well, that the `ODataClient` uses internally to instantiate each time the settings/client/connection is required. 
This way we give complete control over to the DI container.

Does that make sense? Do I miss something? I'm willing to PR this if you'd consider it.

**Comment by weitzhandler** [comment]
@phatcher, thanks for your examples.

So based on my understanding, we should register the `ODataClient` itself as singleton so the metadata etc. is cached, shouldn't we?

But we'd want the `ODataClientSettings` (with an injected `HttpClient`) to be transient or at most scoped, not singleton.
One of the main purposes of the `IHttpClientFactory` is to renew it because otherwise it doesn't respect DNS changes (https://github.com/dotnet/corefx/issues/11224). The current implementation wouldn't allow that, because it retains the `HttpClient`'s life to the `ODataClient` one's.

The two simple solutions I can think of is either:
- Adding a `Func<HttpClient> OnCreateHttpClient { get; set; }` on the `ODataClientSettings` class, or - Add a `Func<ODataClientSettings> OnCreateSettings { get; set; }` that will be used as a delegate point whenever we need a settings instance.

Does that make sense? Do I miss something? I'm willing to PR this if you'd consider it.

**Comment by weitzhandler** [comment]
@phatcher, thanks for your examples.

So based on my understanding, we should register the `ODataClient` itself as singleton so the metadata etc. is cached, shouldn't we?

But we'd want the `ODataClientSettings` (with an injected `HttpClient`) to be transient or at most scoped, not singleton.
One of the main purposes of the `IHttpClientFactory` is to renew it because otherwise it doesn't respect DNS changes (https://github.com/dotnet/corefx/issues/11224). The current implementation wouldn't allow that, because it retains the `HttpClient`'s life to the `ODataClient` one's.

The two simple solutions I can think of is either:
- Adding a `Func<HttpClient> OnCreateHttpClient { get; set; }` on the `ODataClientSettings` class, or - Add a `Func<ODataClientSettings> OnCreateSettings { get; set; }` that will be used as a delegate point whenever we need a settings instance.

Does that make sense? Do I miss something? I'm willing to PR this if you'd consider it.

**Comment by weitzhandler** [comment]
Please see my commit here: https://github.com/simple-odata-client/Simple.OData.Client/compare/master...weitzhandler:dependency-injection

The disposal of the handlers and clients provided by DI, is also the job of the container, and should not be disposed, I changed that too.
