### ISSUE TITLE
Actions REQUIRE a return type, do no work with no return type and 200 return status

### ISSUE THREAD

**Issue by NetTecture** [object/Simple.OData.Client#513]
Let's define a simple action on an object called Serviceprovider that has a key of type GUID:

```
            builder.EntityType<ServiceProvider>()
                .Action("Invite")
                .InNamespace("Operations");
```

There obviously is also an EntitySet, I will jus skip it for now. The metadata for the action is... 

```
<Action Name="Invite" IsBound="true">
<Parameter Name="bindingParameter" Type="PropertyCore.ServiceProvider"/>
<Annotation Term="Org.OData.Core.V1.OptionalParameter"/>
</Parameter>
</Action>
```

Nice. Like it.

The Metadata of ServiceProvider is 

```
<EntityType Name="ServiceProvider">
<Key>
<PropertyRef Name="Identity"/>
</Key>
<Property Name="Identity" Type="Edm.Guid" Nullable="false"/>
```

Just showing the start, other properties are not relevant.

I want my own mapping schema, and I use namespaces (which somehow never make it into any example), so I define the action as:

        [HttpPost()]
        [ODataRoute("ServiceProvider({identity})/Operations.Invite")]
        public IActionResult ActionOperationsInvite(Guid identity)

Works.

Sadly, what do I return? There is no return type, so....

`            return Ok();
`
No, does not work:

```
Result StackTrace:	
at Microsoft.OData.Json.JsonReaderExtensions.ValidateNodeType(IJsonReader jsonReader, JsonNodeType expectedNodeType)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStartImplementation(ODataPayloadKind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ReadPayloadStart(ODataPayloadKind payloadKind, PropertyAndAnnotationCollector propertyAndAnnotationCollector, Boolean isReadingNestedPayload, Boolean allowEmptyPayload)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Simple.OData.Client.V4.Adapter.ResponseReader.ReadResponse(ODataReader odataReader)
   at Simple.OData.Client.V4.Adapter.ResponseReader.GetResponseAsync(IODataResponseMessageAsync responseMessage)
   at Simple.OData.Client.ODataClient.ExecuteRequestWithResultAsync[T](ODataRequest request, CancellationToken cancellationToken, Func`2 createResult, Func`1 createEmptyResult, Func`1 createBatchResult)
   at Simple.OData.Client.ODataClient.ExecuteActionAsync(FluentCommand command, CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.ExecuteAsEnumerableAsync(FluentCommand command, CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.ExecuteAsync(FluentCommand command, CancellationToken cancellationToken)
   at Tests.Api.Odata.Web.Controllers.ServiceProviderTests.InviteWithEmail() in C:\Work\OBB\Source.Backend\Tests.Api.Odata.Web\Controllers\ServiceProviderTests.cs:line 51
Result Message:	
Test method Tests.Api.Odata.Web.Controllers.ServiceProviderTests.InviteWithEmail threw exception: 
Microsoft.OData.ODataException: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected.
```

There is no return type defined, so none should be expected. Not sure what the OData spec says here, but this is a case where a simple HTTP status code 200 actually indicates all is ok, done.

Just to indicate, the test query is:

        [TestMethod()]
        public async Task InviteWithoutEmail()
        {
            var c = new ODataClient(TestSetup.ClientSettings);
            var identity = await c
                .For<OdataApi.ServiceProvider>()
                .Select(x => x.Identity)
                .Top(1)
                .FindScalarAsync<Guid>();
            await c
                .For<OdataApi.ServiceProvider>()
                .Key(identity)
                .Action("Invite")
                .ExecuteAsync();
        }

(because i fist need to pull an identity so know where to call that).

**Comment by object** [comment]
Thanks for the bug report. I will investigate it.

**Comment by object** [comment]
I checked a similar case available in Microsoft TripPin OData sample, the service exposes ShareTrip action that doesn't doesn't return anything. The test (part of the Simple.OData.Client integration tests) works fine, but the service returns 204 No Content instead of 200 OK.

According to OData specs, "A request that does not create a resource returns 200 OK if it is completed successfully and the value of the resource is not null. In this case, the response body MUST contain the value of the resource specified in the request URL."

So I believe you should change the service implementation to return 204.

**Comment by NetTecture** [comment]
AAAAAAH. Yeah. Nice. Accepted and I flag an error with Microsoft because (not only their documentation etc.) but this ia change they could easily do on an OK for soemthing return type void.

**Comment by NetTecture** [comment]
@object You know, now that I think about it - maybe yuo should give a better bug report there. SImple Odata and such. I am NOT sure how many authros are aware of that little issue with required 204 return at this point. As you have the metadata, you could run a check.

**Comment by object** [comment]
My lib wraps Microsoft OData libraries so I must rely on their expectations. If OData spec requires service to supply response when returning 200 and it doesn't, then the best thing I can is to make sure the error that Microsoft response parser encounters will be forwarded to the client. I'd rather not bring in an error mapping layer for improperly implemented services.
