### ISSUE TITLE
Could not load file or assembly 'Simple.OData.Client.V3.Adapter, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by ODataSyd** [object/Simple.OData.Client#517]
Hi ,

 I am using Simple.OData.Client package 5.2.2 . I am using the API FindEntriesAsync and getting an error at runtime . 

When I looked at the issue ,  when i build the dependent dll's for my code the Simple.OData.Client.V3.Adapter was generted with a version 0.0.0.0 but at run time when i used FinEntriedAsync internally the Dll that is trying to load is not having the version number in it .

So as a result I am getting the following error : 

 Unable to load OData adapter from assembly Simple.OData.Client.V3.Adapter ---> System.IO.FileNotFoundException: Could not load file or assembly 'Simple.OData.Client.V3.Adapter, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load the specified file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Simple.OData.Client.AdapterFactory.LoadAdapterAssembly(String modelAdapterAssemblyName)
   at Simple.OData.Client.AdapterFactory.LoadModelAdapter(String modelAdapterAssemblyName, String modelAdapterTypeName, Object[] ctorParams)
   --- End of inner exception stack trace ---
   at Simple.OData.Client.AdapterFactory.LoadModelAdapter(String modelAdapterAssemblyName, String modelAdapterTypeName, Object[] ctorParams)
   at Simple.OData.Client.AdapterFactory.CreateAdapter(String metadataString)
   at Simple.OData.Client.MetadataCache..ctor(String key, String metadataDocument)
   at Simple.OData.Client.Session.<>c__DisplayClass14_0.<<ResolveAdapterAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Simple.OData.Client.MetadataCache.GetOrAddAsync(String key, Func`2 valueFactory)
   at Simple.OData.Client.Session.ResolveAdapterAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.FindEntriesAsync(FluentCommand command, Boolean scalarResult, ODataFeedAnnotations annotations, CancellationToken cancellationToken)

I am not sure why the actual dll that is generated having a version 0.0.0.0 and the run time reflection is looking for a dll with out the version ? Any ideas how to resolve this issue and is it possible to generate the correct version number instead of 0.0.0.0

Thanks,
G.

**Comment by ODataSyd** [comment]
Hi Guys ,

 Any help in this regard or any suggestions ?

Thanks,
G.

**Comment by object** [comment]
I am not sure I understand what do you mean by generated version 0.0.0.0. The library DLLs have the non-zero version. Next, can you check that the actual DLL file is present in the binary folder of your application? Begin with checking this, make sure all referenced and dependent DLLs are there and check if the application works. Then next step would be to find out why they were missing.

**Comment by ODataSyd** [comment]
Hi ,

 I will give you more details related to this error .

 Step 1 : I used the simple.odata.clinet 5.2.2 package from nuget and published the project . When I published the project , I can see in the published folders all the dll's required including Simple Odata dll's

Step 2 : 
Our application/framework is loading all the dll's , that means we loaded all the dll's that were published in  Step 1 .  Once we loaded all the dll's for example if i look at the full name of Simple Odata V3 Adapter Dll it is "Simple.OData.Client.V3.Adapter, **Version=0.0.0.0**, Culture=neutral, PublicKeyToken=null"

Step 3 : 
Now at run time i am trying to get a key using query.findentryasync method , when i use the query.findentry async method simple odata internally trying to load "private const string AdapterV3AssemblyName = "Simple.OData.Client.V3.Adapter" in class Simple.OData.Client.AdapterFactory" when this assembly is getting loaded , our framework is using 

private Assembly Assembly_Resolving(AssemblyLoadContext arg1, AssemblyName arg2)
        {
            return objectAssemblies.FirstOrDefault(a => a.FullName == arg2.FullName && a.GetName().Version == arg2.Version);
        }

So what our framework is trying to do is : from the loaded dll's ( with version 0.0.0.0 )  from Step 2 trying to match the one simple odata client is loading from Step 3 ( Simple.OData.Client.V3.Adapter). As the Step 3 dll doesnt have any version and the loaded dll has a version v 0.0.0.0 , our framework is throwing an error . 

If I modify

private const string AdapterV3AssemblyName = "Simple.OData.Client.V3.Adapter, **Version=0.0.0.0** " in class Simple.OData.Client.AdapterFactory" it would work fine as it matches to the right dll from the published dll from step 1 .

If still not understood , please let me know.

Thanks,
G.

**Comment by object** [comment]
Hmm, I will investigate this further and come back to you.

**Comment by object** [comment]
I have now released the package 5.5.0-beta2 which should fix this issue.
