### ISSUE TITLE
Calling Action that expects a Collection of Complex types - error.

### ISSUE THREAD

**Issue by NetTecture** [object/Simple.OData.Client#541]
Using the current 5.5 release, the followingcode results in an error.

First the Metadata:

The complex type:

```
<ComplexType Name="InspectionDutyChange">
<Property Name="Identity" Type="Edm.Guid" Nullable="false"/>
<Property Name="IsDisabled" Type="Edm.Boolean" Nullable="false"/>
</ComplexType>
```

is called on an action:

```
<Action Name="BulkChange" IsBound="true">
<Parameter Name="bindingParameter" Type="Collection(PropertyCore.InspectionDuty)"/>
<Parameter Name="Comment" Type="Edm.String" Unicode="false"/>
<Parameter Name="Changes" Type="Collection(PropertyCore.InspectionDutyChange)"/>
</Action>
```

Like always, I am trying to call it in a unit test to validate the backend works ;)

```
            await c
                .For<OdataApi.InspectionDuty>()
                .Action("BulkChange")
                .Set(new {
                    Comment = "comment try",

                    Changes = (ICollection<InspectionDutyChange>) new List<InspectionDutyChange> {
                        new InspectionDutyChange() { Identity = Guid.NewGuid(), IsDisabled = false },
                        new InspectionDutyChange() { Identity = Guid.NewGuid(), IsDisabled = false },
                    },
                })
                .ExecuteAsync();
```

I get an error that I seem unable to work around, whenver I have Changes defined (i.e. it works perfectly if I remove the Changes collection from definition metadata insert parameter) If it exists, I seem unable to work around this error - I tried all types of elements, from arrays to lists to the ICollection you see here:

Microsoft.OData.ODataException: Unsupported primitive type. A primitive type could not be determined for an instance of type 'Api.Odata.InspectionDutyChange'.

And I obviously have a nice stack trace:

Result StackTrace:	
at Microsoft.OData.ValidationUtils.ValidateIsExpectedPrimitiveType(Object value, IEdmPrimitiveTypeReference valuePrimitiveTypeReference, IEdmTypeReference expectedTypeReference)
   at Microsoft.OData.JsonLight.ODataJsonLightValueSerializer.WritePrimitiveValue(Object value, IEdmTypeReference actualTypeReference, IEdmTypeReference expectedTypeReference)
   at Microsoft.OData.JsonLight.ODataJsonLightCollectionWriter.WriteCollectionItem(Object item, IEdmTypeReference expectedItemType)
   at Microsoft.OData.ODataCollectionWriterCore.InterceptException(Action action)
   at Microsoft.OData.TaskUtils.GetTaskForSynchronousOperation(Action synchronousOperation)
--- End of stack trace from previous location where exception was thrown ---
   at Simple.OData.Client.V4.Adapter.RequestWriter.WriteOperationParameterAsync(ODataParameterWriter parameterWriter, IEdmOperationParameter operationParameter, String paramName, Object paramValue)
   at Simple.OData.Client.V4.Adapter.RequestWriter.WriteActionContentAsync(String method, String commandText, String actionName, String boundTypeName, IDictionary`2 parameters)
   at Simple.OData.Client.RequestWriterBase.CreateActionRequestAsync(String commandText, String actionName, String boundTypeName, IDictionary`2 parameters, Boolean resultRequired)
   at Simple.OData.Client.ODataClient.ExecuteActionAsync(FluentCommand command, CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.ExecuteAsEnumerableAsync(FluentCommand command, CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.ExecuteAsync(FluentCommand command, CancellationToken cancellationToken)
   at Tests.Api.Odata.Web.IdentityEntityTestBase`1.BulkChange() in C:\Work\OBB\Source.Backend\Tests.Api.Odata.Web\IdentityEntityTestBase.cs:line 41

This looks ridiculously similar to #282 - in fact outright identical - except this bug was fixed for 4.2.4 about 2 years ago and closed Sep 15 2016. Unit test missing? Did MS introduce an error in their latest library releases? How can I work around it?

**Comment by richb81** [comment]
Is there any update on this? I'm not able to pass complex type to an action?
"The parameter 'Value' is of Edm type kind 'Complex'. You cannot call WriteValue on a parameter that is not of Edm type kinds 'Primitive', 'Enum' or 'Complex'."

**Comment by ysmoradi** [comment]
I've the same issue )-:
