### ISSUE TITLE
Could not find a constructor for type 'Collection`1' with the following argument types: IEnumerable`1

### ISSUE THREAD

**Issue by twastvedt** [object/Simple.OData.Client#550]
I'm using Simple.OData.Client with a Dynamics 365 CRM instance, using the fluent typed interface with classes generated by [OData v4 Client Code Generator](https://marketplace.visualstudio.com/items?itemName=bingl.ODatav4ClientCodeGenerator). It's been working great: this is an awesome tool. Thank you! One issue. When I try to use Expand, I get the error: ``Simple.OData.Client.Extensions.ConstructorNotFoundException: 'Could not find a constructor for type 'Collection`1' with the following argument types: IEnumerable`1'``.

Stack trace:
```
   at Simple.OData.Client.Extensions.ExpressionActivator.CreateActivator(Type type, Type[] parameters)
   at Simple.OData.Client.Extensions.DictionaryExtensions.<>c__DisplayClass16_1.<ConvertCollection>b__0(Tuple`2 t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ConvertCollection(Type type, Object itemValue)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject(IDictionary`2 source, Type type, String dynamicPropertiesContainerName, Boolean dynamicObject)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject[T](IDictionary`2 source, String dynamicPropertiesContainerName, Boolean dynamicObject)
   at Simple.OData.Client.FluentClientBase`2.ConvertResult(IDictionary`2 result, String dynamicPropertiesContainerName)
   at Simple.OData.Client.FluentClientBase`2.<>c__DisplayClass85_0.<FilterAndTypeColumnsAsync>b__0(IDictionary`2 z)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
```
Not sure what to do or how to debug. I'm thinking maybe the generator is creating something that Simple.OData.Client doesn't like, but I'm not sure how to fix it. Thanks!

**Comment by twastvedt** [comment]
The generated code from Dynamics CRM (~40 mb) got to be too much, so I started creating my own POCO classes. I used IEnumerable for collection properties and that seems to be working well. If there are no plans to support the output of the OData v4 Client Code Generator then this can be closed. Thanks!

**Comment by object** [comment]
I believe this is fixed now. Support for System.Collections.ObjectModel.Collection will be released in 5.6.

**Comment by robertmclaws** [comment]
I'm running into the same issue with ObervableCollections in Blazor on .NET 6.0:

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find a constructor for type 'ObservableCollection`1' with the following argument types: IEnumerable`1
Simple.OData.Client.Extensions.ConstructorNotFoundException: Could not find a constructor for type 'ObservableCollection`1' with the following argument types: IEnumerable`1
   at Simple.OData.Client.Extensions.ExpressionActivator.CreateActivator(Type type, Type[] parameters)
   at Simple.OData.Client.Extensions.DictionaryExtensions.<>c__DisplayClass16_0.<ConvertCollection>b__0(Tuple`2 t)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Tuple`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Simple.OData.Client.Extensions.ActivatorDelegate, Simple.OData.Client.Core, Version=5.24.0.0, Culture=neutral, PublicKeyToken=58885f4495efc1ae]].GetOrAdd(Tuple`2 , Func`2 )
   at Simple.OData.Client.Extensions.DictionaryExtensions.ConvertCollection(Type type, ITypeCache typeCache, Object itemValue)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ConvertValue(Type type, ITypeCache typeCache, Object itemValue)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject(IDictionary`2 source, ITypeCache typeCache, Type type, Boolean dynamicObject)
   at Simple.OData.Client.Extensions.DictionaryExtensions.ToObject[JourneyTemplate](IDictionary`2 source, ITypeCache typeCache, Boolean dynamicObject)
   at Simple.OData.Client.FluentClientBase`2[[CloudNimble.BurnRate.Core.JourneyTemplate, CloudNimble.BurnRate.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Simple.OData.Client.IBoundClient`1[[CloudNimble.BurnRate.Core.JourneyTemplate, CloudNimble.BurnRate.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Simple.OData.Client.Core, Version=5.24.0.0, Culture=neutral, PublicKeyToken=58885f4495efc1ae]].ConvertResult(IDictionary`2 result, String dynamicPropertiesContainerName)
...
```

I thought at first it might be the Linker, but I don't believe that is the case.

**Comment by robertmclaws** [comment]
Actually, it looks like it was the linker. If you run into this issue in Blazor, add the following code to the classes that are not working:

```csharp
var collection = new ObservableCollection<string>(new List<string>() as IEnumerable<string>);
collection = null;
```
