### ISSUE TITLE
WebRequestException : Internal Server Error on request

### ISSUE THREAD

**Issue by ruimaciel** [object/Simple.OData.Client#555]
Consider the following member function:

```
    public async void Run()
    {
        var client = new ODataClient("https://catalogue.onda-dias.eu/dias-catalogue/");
        var products = await client
            .FindEntriesAsync("Products");
    }
```

Running the above function in a unit test throws the following exception:

```
Starting test execution, please wait...
[xUnit.net 00:00:01.18]     MyTests.test_ODataClient.TestName [FAIL]
Failed   MyTests.Tests.test_ODataClient.TestName
Error Message:
 Simple.OData.Client.WebRequestException : Internal Server Error
Stack Trace:
   at Simple.OData.Client.RequestRunner.PostExecute(HttpResponseMessage responseMessage)
   at Simple.OData.Client.RequestRunner.ExecuteRequestAsync(ODataRequest request, CancellationToken cancellationToken)
   at Simple.OData.Client.Session.SendMetadataRequestAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.Session.ResolveMetadataAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.Session.<>c__DisplayClass14_0.<<ResolveAdapterAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Simple.OData.Client.EdmMetadataCache.GetOrAddAsync(String key, Func`2 valueFactory)
   at Simple.OData.Client.Session.ResolveAdapterAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.RequestBuilder.GetRequestAsync(Boolean scalarResult, CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.FindAnnotatedEntriesAsync(String commandText, Boolean scalarResult, ODataFeedAnnotations annotations, CancellationToken cancellationToken)
   at Simple.OData.Client.ODataClient.FindEntriesAsync(String commandText, Boolean scalarResult, ODataFeedAnnotations annotations, CancellationToken cancellationToken)
   at MyTest.OdataClientService.Run() in /home/rmam/development/MyTest/tests/ODataClient.cs:line 15

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.7702 Seconds
```

Even if the exception is designed to be an appropriate result to the server response, the output could still be informative and provide clues to what the problem might be beyond an internal server error.

**Comment by NetTecture** [comment]
The problem with that is that you have a mental disconnect.

The exception is thrown by the server. The SERVER fails to provide a sensible error message, instead returning a HTTP status 500. ANY information may be in the payload, but it is not sensible by default - 500 is a "ok, i do not catch this error, so let the runtime return 500 and log it) error.

Simple.OData.Client is not a server level framework, so - it is not responsible for handling this. This is like accusing the fax to order your pizza from the wrong shop. You have to direct your bug report to whoever wrote and maintains the server.

**Comment by object** [comment]
Judging from the stack trace, the error occurs very early, at the stage of resolving OData adapter, which includes requesting service metadata. And it is metadata request that causes server to throw 500.
As @NetTecture pointed out, there is very little that can be done with such errors. If server denies the request with such broad error message (that basically means "something went wrong on a server side"), then it's just to inspect what exactly failed in the server app. Client is not capable to improve this error in any way.
