### ISSUE TITLE
None supported mimetype with Post request

### ISSUE THREAD

**Issue by mknoos** [object/Simple.OData.Client#91]
Im running .Net 4.5 and Simple.Odata:client v 4.0.9.
When running post requests i get the following exception from the client.

System.AggregateException: One or more errors occurred. ---> Microsoft.Data.OData.ODataContentTypeException: A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/atom+xml;type=entry, application/atom+xml, application/json;odata=verbose, application/json' matches the content type 'application/xml; charset=utf-8'.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Simple.OData.Client.ODataClient.<InsertEntryAsync>d__d4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Simple.OData.Client.BoundClient`1.<InsertEntryAsync>b__27(Task`1 x)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at APIRestTest.DelegationTest.<CreateAndDeleteDelegation>d__40.MoveNext() in d:\Projects\APIRestTest\DelegationTest.cs:line 48
---> (Inner Exception #0) Microsoft.Data.OData.ODataContentTypeException: A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/atom+xml;type=entry, application/atom+xml, application/json;odata=verbose, application/json' matches the content type 'application/xml; charset=utf-8'.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Simple.OData.Client.ODataClient.<InsertEntryAsync>d__d4.MoveNext()<---

is there something that i need to do during the setup.of the client?

**Comment by object** [comment]
Can you try the latest version of Simple.OData.Client? I believe 4.2 and 4.3 should work fine. Let me know.

**Comment by mknoos** [comment]
Great thank now it works!
