### ISSUE TITLE
Error when i try to Insert a new object with derived class association 

### ISSUE THREAD

**Issue by manusisnova** [object/Simple.OData.Client#97]
Hi, i have another issue when i try to insert a new object, 
derived from https://github.com/object/Simple.OData.Client/issues/90#event-273338638

My metadata file is here https://dl.dropboxusercontent.com/u/38813484/metadata.zip

And my code is 

serviceUri = new Uri("http://localhost:7675/simple.odata.clienttest.svc/");
            ODataClientSettings odataClientSettings = new ODataClientSettings(serviceUri.AbsoluteUri);
            ODataClient odataclientTest = new ODataClient(odataClientSettings);
            var category = await odataclientTest
                .For<BaseCategory>("Simple_OData_ClientTest_DataModelCode_BaseCategory").As<Category>("Simple_OData_ClientTest_DataModelCode_Category").FindEntryAsync();
            Product newproduct = new Product();
            newproduct.ProductName = "Test6";
            newproduct.UnitPrice = 18m;
            newproduct.Category = category;

            var product = await odataclientTest
                .For<Product>("Simple_OData_ClientTest_DataModelCode_Product").As<Product>("Simple_OData_ClientTest_DataModelCode_ExtendedProduct")
                .Set(newproduct)
                .InsertEntryAsync();

Thanks for your help

**Comment by object** [comment]
Thank you, and what is the error you are getting? Can you paste generated URI and the response?

**Comment by manusisnova** [comment]
The error is: {"Value cannot be null.\r\nParameter name: source"}, Stacktrace:
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Simple.OData.Client.V3.Adapter.RequestWriter.WriteLink(ODataWriter entryWriter, ODataEntry entry, String linkName, IEnumerable`1 links)
   at Simple.OData.Client.V3.Adapter.RequestWriter.<WriteEntryContentAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Simple.OData.Client.RequestWriterBase.<CreateInsertRequestAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Simple.OData.Client.ODataClient.<ExecuteInsertEntryAsync>d__114.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Simple.OData.Client.ODataClient.<InsertEntryAsync>d__d4.MoveNext()

Where i get geterated URI?

**Comment by object** [comment]
You can look at generated URLs using Fiddler application that will show both URL and response. But it looks like the error occurs before request is sent, so I believe it will be sufficient with the information I already have.

**Comment by object** [comment]
I made some fixes in the version 4.4.0. Please check it out.

**Comment by manusisnova** [comment]
Fixed it, thanks a lot
