### ISSUE TITLE
Getting System.AggregateException while client execution

### ISSUE THREAD

**Issue by ashuthinks** [object/Simple.OData.Client#98]
When I try to execute "Action" 
public async  Task<ValidationResult> Validation<T>(T entity)
        {   var result = await this.For<ModelClass>()
                  .Action("Validate")
                .ExecuteAsSingleAsync();
            return new ValidationResult();
        }
I'm getting following exception although i'm using latest nuget Simple.OData.V4.Client 4.3.2.

 at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Simple.OData.Client.FluentClientBase`1.<>c__DisplayClass7.<RectifyColumnSelectionAsync>b__6(Task`1 x)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Framework.Validation.Client.ValidationClient.<Validation>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Framework.Validation.Client.TestApp.Form1.<Form1_Load>d__1.MoveNext() in 

What is wrong here ? any clue ?

**Comment by object** [comment]
Difficult to say except that you are getting an exception somewhere down the pipeline. Can you debug it and break at the exception? Can you trace HTTP communication and see what response are you getting from the OData service?

**Comment by ashuthinks** [comment]
Actually in simple word I'm unable to execute "Funstions" or "Actions" :(
could you please give me any link where i can find simple example to execute both ? detail link ?

**Comment by object** [comment]
Can you check this tutorial? It has functions/actions section.

http://www.odata.org/blog/advanced-odata-tutorial-with-simple-odata-client/

If you have any problems I need a dump of HTTP communication (using Fiddler or similar tool) and a copy of the metadata document. Without it it's hard to understand what's going on.

**Comment by object** [comment]
Unable to reproduce.
